services:
  portfolio_nginx:
    image: nginx:stable-alpine-slim
    container_name: portfolio_nginx
    restart: always
    networks:
      - proxy
    environment:
      - NGINX_PORT=8080
    volumes:
      - ./html:/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.portfolio-nginx.rule=(`portfolio.nimblecloud.app`)"
      - "traefik.http.routers.portfolio-nginx.entrypoints=http,https"
      - "traefik.http.routers.portfolio-nginx.tls=true"
      - "traefik.http.services.portfolio-nginx.loadbalancer.server.port=8080"

  portfolio_datavis_api:
    image: ${DATA_VIS_IMAGE}
    container_name: portfolio_datavis_api
    restart: unless-stopped
    environment:
      - DATA_VIS_IMAGE=${DATA_VIS_IMAGE}
      - JWT_SECRET=${DATA_VIS_JWT_SECRET}
      - DB_URL=${DATA_VIS_DB_URL}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.portfolio_datavis_api.rule=Host(`portfolio-datavis-api.nimblecloud.app`)"
      - "traefik.http.routers.portfolio_datavis_api.entrypoints=https"
      - "traefik.http.routers.portfolio_datavis_api.tls=true"
      - "traefik.http.services.portfolio_datavis_api.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
